
books = [
    {
        "id": 1,
        "title": "python",
        "author": "anmol kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-01-01",
        "page_count": 1234,
        "language": "english",
    },
    {
        "id": 2,
        "title": "think python",
        "author": "pushkar kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-02-01",
        "page_count": 5678,
        "language": "english",
    },
    {
        "id": 3,
        "title": "python core",
        "author": "himanshu kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-03-01",
        "page_count": 9012,
        "language": "english",
    },
    {
        "id": 4,
        "title": "python advance",
        "author": "aman kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-04-01",
        "page_count": 3456,
        "language": "english",
    },
    {
        "id": 5,
        "title": "python oops",
        "author": "harsh kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-04-01",
        "page_count": 7893,
        "language": "english",
    },
    {
        "id": 6,
        "title": "python dsa",
        "author": "prinve kumar",
        "publisher": "vidyapeeth",
        "published_date": "2026-04-01",
        "page_count": 5642,
        "language": "english",
    },
]
